[context.dev.environment]
PUBLIC_SANITY_VISUAL_EDITING_ENABLED = true

[dev]
command = "npm run dev"
framework = "#custom"
targetPort = 4321
port = 8888

[[redirects]]
from = "/admin*"
to = "/admin"
status = 301
force = true